# Generated by Django 4.1.7 on 2023-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpagemodel',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
