# Generated by Django 4.1.7 on 2023-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_vendorpagemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseordermodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.IntegerField(blank=True, default=0, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('items', models.JSONField(default=dict)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('quality_rating', models.FloatField(blank=True, default=0, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Purchase_Order',
            },
        ),
    ]
