# Generated by Django 4.1.7 on 2023-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_purchaseordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
