# Generated by Django 4.1.7 on 2023-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_purchaseordermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='delete_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
