# Generated by Django 4.1.7 on 2023-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_purchaseordermodel_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='acknowledged_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vendorpagemodel',
            name='completed_status_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
