# Generated by Django 4.1.7 on 2023-12-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0006_purchaseordermodel_acknowledged_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='refulfillment_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
